### ISSUE TITLE
Launching AEPsych server error

### ISSUE THREAD

**Issue by garcikar** [facebookresearch/aepsych#341]
Hello @crasanders !

My name is Karen Garcia, and I am a data analyst at Oregon Health and Science University. I recently came across your research paper _Adaptive Nonparametric Psychophysics_, and I am very interested in using AEPsych.

Mike Shvartsman gave me your name as a point person for answering questions about AEPsych. I started following the tutorial on your documentation website: https://aepsych.org/#quickstart

1. I tried launching it in server mode with this command from the tutorial:

aepsych_server --port 5555 --ip 0.0.0.0 database --db mydatabase.db

and I got this error :
<img width="1102" alt="Screenshot 2024-04-16 at 10 07 04 AM" src="https://github.com/facebookresearch/aepsych/assets/166537828/7a8a6b64-b6db-4c19-adb9-12583774d1c0">

2. Then I removed "database" from the command since that's what the error message told me. After that I got a different issue. It seems to be waiting for a connection but it just stays stuck with that. I have waited for hours at a time and a connection never starts. 

<img width="1102" alt="Screenshot 2024-04-16 at 10 07 40 AM" src="https://github.com/facebookresearch/aepsych/assets/166537828/884a4310-ff97-493a-997b-a5f5f7ba302d">

If I could get some clarity with this issue I would greatly appreciate it. 

Thank you for your time and consideration.

**Comment by crasanders** [comment]
Hello, I apologize for not seeing this sooner! The latter behavior is the expected behavior. The AEPsych server has started, and it is waiting to receive messages from a client. Please see [this tutorial](https://aepsych.org/tutorials/data_collection_analysis_tutorial) for an example of how to communicate with the server using a Python client. We also have [Unity and MATLAB clients](https://github.com/facebookresearch/aepsych/tree/main/clients).
